### ISSUE TITLE
Request for Test Set Results on SemanticKITTI Benchmark

### ISSUE THREAD

**Issue by npurson** [Jiawei-Yao0812/NDCScene#1]
Hi there, I noticed that the provided SemanticKITTI results appear to be reported on the validation set. It would be greatly appreciated if you could provide results for the test set as well, as this would facilitate better comparisons.

Additionally, I think the [SemanticKITTI benchmark on Papers with Code](https://paperswithcode.com/sota/3d-semantic-scene-completion-from-a-single-1) typically displays test results, where your reported results may need to be updated to align with this practice.

**Comment by Alexander-Yao** [comment]
> Thank you for bringing up this important point regarding the SemanticKITTI results. I understand your concern and agree that providing results on the test set is crucial for a comprehensive evaluation.
> 
> The provided mIoU of test set in NDC-Scene supplementary material is 12.58 and updated on the [SemanticKITTI benchmark on Papers with Code](https://paperswithcode.com/sota/3d-semantic-scene-completion-from-a-single-1).
