### ISSUE TITLE
Issue with nyu dataset

### ISSUE THREAD

**Issue by fdengmark** [Jiawei-Yao0812/NDCScene#2]
I'm trying to run the inference part on NYUv2 dataset. However, the nyuv2 dataset download link you have pasted is no longer vaild. I have downloaded the NYUv2 dataset from the home page, but looks like the preprocess.py is not able to run directly on "nyu_depth_v2_labeled.mat". 

it look's like the preprocess.py is look for some .bin files from NYURoot, and I'm very confuse about where are thoes ".bin" files come from.

Can you upload the NYUv2 dataset again?

Thank you so much

**Comment by Jiawei-Yao0812** [comment]
Hi, here is the updated [NYUv2 dataset](https://drive.google.com/file/d/1n8rXSVpWK_Vjcu2P1KKTswBdvEI-U7Uv/view?usp=sharing).

**Comment by fdengmark** [comment]
Thank you so much!!

**Comment by Jiawei-Yao0812** [comment]
Resolved
