### ISSUE TITLE
kitti-voxel doesn't have labels in sequences 11-21

### ISSUE THREAD

**Issue by dzrdzrdzr** [Jiawei-Yao0812/NDCScene#3]
kitti-voxel doesn't have labels in sequences 11-21. But preprocess file search on it which means can't be Initialized.

**Comment by dzrdzrdzr** [comment]
by the way the preprocess file in NYC 146 should be:
@hydra.main(config_name="../../config/ndcscene_nyu.yaml")

**Comment by Jiawei-Yao0812** [comment]
Hi @dzrdzrdzr , there is no label available for the test sequences (11-21).  To get the test performance, please refer to the content of this competition website (https://competitions.codalab.org/competitions/22037#learn_the_details-participate).

And thanks for pointing out the preprocess file's issue.
