### ISSUE TITLE
train my dataset

### ISSUE THREAD

**Issue by lzbushicai** [Jiawei-Yao0812/NDCScene#6]
Thank you for your outstanding work. I want to use your model to train my dataset. My dataset contains RGB images and semantic information. how can process my dataset? Also, how can I use your existing model to detect my images?

**Comment by Jiawei-Yao0812** [comment]
Hi @lzbushicai , sorry for the late reply as i have been busy recently. I hope your problem has been successfully solved. 

If not, you could try to voxelise the LiDAR data into a voxel grid and feed into dataloader we provided (change nedd to be made according to your own dataset).

**Comment by lzbushicai** [comment]
I have solved my problems!!!    thank you

**Comment by Alexander-Yao** [comment]
Closed
